main/urls.py
from django.urls import path
from .views import *

app_name='main'
urlpatterns = [
    path('', main, name="showmain"),
    path('posts/', posts, name="posts"),
    path('<int:id>', detail, name="detail"),
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('<str:id>/create_comment', create_comment, name="create_comment"),
    path('<str:id>/delete_comment', delete_comment, name="delete_comment"),
    path('<str:id>/edit_comment', edit_comment, name="edit_comment"),
    path('<str:id>/update_comment', update_comment, name="update_comment"),
]

sns_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    #allauth의 url 연결
    path('accounts/',include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/', mypage, name="mypage"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer=models.ForeignKey(User,on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "post/", blank=True, null=True)

class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post ,on_delete=models.CASCADE, related_name ='comments')
    created_at = models.DateTimeField(auto_now=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:20]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from django.utils import timezone

# Create your views here.
def main(request):
    return render(request, 'main/show.html')

def showmain(request):
    posts = Post.objects.all()
    return render(request, 'main/show.html', {'posts' : posts})

def posts(request):
    posts = Post.objects.all()
    return render(request, 'main/posts.html', {'posts':posts})

def detail(request, id):
    post = get_object_or_404(Post, pk = id)
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'main/detail.html', {'post':post, 'comments':all_comments})

def new(request):
    return render(request, 'main/new.html')

def create(request):
    new_post = Post()
    new_post.title = request.POST['title']
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:detail',new_post.id)

def edit(request, id):
    edit_post = Post.objects.get(id=id)
    return render(request, 'main/edit.html', {'post':edit_post})

def update(request, id):
    update_post = Post.objects.get(id=id)
    update_post.title = request.POST['title']
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.body = request.POST['body']
    if request.FILES.get("image"):
            update_post.image = request.FILES.get("image")
    update_post.save()
    return redirect('main:detail', update_post.id)

def delete(request, id):
    delete_post = Post.objects.get(id=id)
    delete_post.delete()
    return redirect('main:posts')

def create_comment(request, id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=id)
        current_user = request.user
        comment_content = request.POST.get("content")
        Comment.objects.create(content=comment_content, writer=current_user, post=post)
    return redirect("main:detail", id)
    
def edit_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.user == comment.writer:
        return render(request, "main/edit_comment.html", {"comment": comment})
    else:
        return redirect("main:detail", comment.post.id)

def delete_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.user == comment.writer:
        comment.delete()
    return redirect("main:detail", comment.post.id)

def update_comment(request, id):
    comment = Comment.objects.get(id=id)
    comment.content = request.POST.get("content")
    comment.save()
    return redirect("main:detail", comment.post.id)

users/views.py
from django.shortcuts import render
from main.models import Post
from django.contrib.auth.models import User

# Create your views here.
def mypage(request):
    user=request.user
    #로그인한 유저이름과 글 작성자 이름이 동일한 글 필터링
    posts=Post.objects.filter(writer=user)
    return render(request,'users/mypage.html',{'posts':posts})

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{post.title}}</h1>
{% if post.writer %}
    {% if 'user' in post.writer.username %}
        <h3>작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}</h3>
    {% else %}
        <h3>작성자 : {{ post.writer }}</h3>
    {% endif %}
{% else %}
    <h3>작성자 : 알 수 없음</h3>
{% endif %}

날짜 : {{post.pub_date}}
<hr>
{% if post.image %}
    <p><img src = "{{post.image.url}}" alt = "사진" height="500" weigh="500"></p>
{% endif %}
<p>{{post.body}}</p>

<div>
    <form action="{%url 'main:create_comment' post.id%}" method="POST">
        {%csrf_token%}
        <textarea name="content" placeholder="댓글내용입력"></textarea>
        <input type="submit" value="확인">
    </form>
</div>    

<div>
    {% for comment in comments %}
    <div>
        {% if 'user' in comment.writer.username %}
        <h6>작성자 : {{ comment.writer.last_name }} {{ comment.writer.first_name }}</h6>
        {% else %}
        <h6>작성자 : {{ comment.writer }}</h6>
        {% endif %}
    {{comment.content}}<br>
        {% if user == comment.writer %}
        <a href="{% url 'main:edit_comment' comment.id %}">댓글 수정</a>
        <a href="{% url 'main:delete_comment' comment.id %}">댓글 삭제</a>
        {% endif %}
    <hr>
    </div>
    {% endfor %}
</div>

{% if user == post.writer %}
<a href="{% url 'main:edit' post.id%}">글 수정</a>
<a href="{% url 'main:delete' post.id%}">글 삭제</a> 
{% endif %}

<h5><a href = "{% url 'main:posts' %}">글 목록</a></h5>

{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>글 수정하기</h1>
    <form action="{% url 'main:update' post.id%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목 : <input type="text" name="title" value="{{post.title}}"></p>
        <p>사진 : <input type="file" name="image"></p>
        <p>내용 : <textarea name="body" id="" cols="30" rows="10" >{{post.body}}</textarea></p>
        <button type="submit">제출</button>
    </form>
</div>
{% endblock %}

main/templates/main/edit_comment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>EDIT COMMENT</h1>
<form action="{%url 'main:update_comment' comment.id%}" method="POST">
    {%csrf_token%}
    <textarea name="content">{{comment.content}}</textarea>
    <input type="submit" value="확인">
</form>

{% endblock %}

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'main:create' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <p>제목 : <input type="text" name="title"></p>
    <p>사진 : <input type="file" name="image"></p>
    <p>내용 : <textarea type="text" name="body" id="" cols="30" rows="10"></textarea></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
    <br>
    <h1>글 목록</h1><br>
    <div>
        {% for post in posts %}
        <div>
            <h3>{{post.title}}</h3>
            {% if post.writer %}
                {% if 'user' in post.writer.username %}
                    <h3>작성자 : {{ post.writer.last_name }} {{ post.writer.first_name }}</h3>
                {% else %}
                    <h3>작성자 : {{ post.writer }}</h3>
                {% endif %}
            {% else %}
                <h3>작성자 : 알 수 없음</h3>
            {% endif %}   
            
            {{post.summary}}<br>
            <a href="{% url 'main:detail' post.id %}">...자세히</a><hr>
        </div>
        {% endfor %}
    </div>
{% else %}

    <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
    <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    
{% endif %}
{% endblock %}

main/templates/main/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
    <title>dudtlstm</title>
</head>
<h1>Post List</h1>
<h5><a href = "{% url 'main:posts' %}">글 목록 보기</a></h5>
<h4 style="text-align:right"><a href="{% url 'main:new' %}">나도 글쓰기!</a></h4>
<hr>
<body>
    <div id="jb-container">
        <div id="jb-header">
            <h1>Who am I?</h1>
        </div>
        <div id="jb-content">
            <center><img src="{% static 'images/브이사진.jpg' %}" height="240" weigh="240"></center>
            <div class="Name">
                <h1>Name</h1>
            </div>
            <div class="shin">
                <p>박영신(朴英信)</p>
            </div>
            <div class="Age">
                <h1>Age & Gender</h1>
            </div>
            <div class="zerotwo">
                <p>21살(02년생) & 여자</p>
            </div>
            <div class="Birthday">
                <h1>Birthday</h1>
            </div>
            <div class="twoten">
                <p>2의 10승</p>
                <p>(= 1024 ㅎ ㅎ)</p>
            </div>
            <div class="Major">
                <h1>Major</h1>
            </div>
            <div class="computer">
                <p>영어영문학부</p>
                <p>영영 최고입니다~~</p>
            </div>
            <div class="MBTI">
                <h1>MBTI</h1>
            </div>
            <center>
                <p><img src="{% static 'images/엠바탸이.jpg' %}" height="170" weigh="170"></p>
            </center>
            <div class="INFJ">
                <p>거의 반반이지만 뼛속까지 "INFJ"</p>
                <p>사람마다 대하는 게 많이 다르지만 친해지면 내가 I라는 걸 아무도 못 믿음.</p>
                <p>친해지면 영락없는 개구쟁이가 됨 ^_^</p>
                <p>친해지고 싶어요 모두들...!!</p>
            </div>
            <div class="Hobby">
                <h1>Hobby</h1>
                <img src="{% static 'images/하늘사진1.jpg' %}" style="margin: 0 auto;" height="130" weigh="130" />
                <img src="{% static 'images/하늘사진2.jpg' %}" style="margin: 0 auto;" height="130" weigh="130" />
                <img src="{% static 'images/하늘사진이요.jpg' %}" style="margin: 0 auto;" height="130" weigh="130" />
                <img src="{% static 'images/하늘사진3.jpg' %}" style="margin: 0 auto;" height="130" weigh="130" />
                <img src="{% static 'images/하늘사진4.jpg' %}" style="margin: 0 auto;" height="130" weigh="130" />
            </div>
            <div class="sky">
                <p>❝ONE❞ 하늘 보기, 하늘 및 풍경 사진 찍기⛅</p>
                <p>해 질 때의 노을을 너무나 사랑하는 편...</p>
                <img src="{% static 'images/바다사진1.jpg' %}" style="margin: 0 auto;" height="150" weigh="150" />
                <img src="{% static 'images/바다사진2.jpg' %}" style="margin: 0 auto;" height="150" weigh="150" />
                <div class="ocean">
                    <p>❝TWO❞ 바다 보기⛱</p>
                    <p>보면서 힐링되는 건 뭐든 좋아하는 것 같아요 !!</p>
                </div>
                <p>❝THREE❞ 운동⚽</p>
                <p>찍어 둔 사진은 없지만 배드민턴, 등산, 축구 등 운동하는 것도 너무 좋아해요 !</p>
                <img src="{% static 'images/만두사진.jpg' %}" style="margin: 0 auto;" height="130" weigh="130" />
                <p>❝FOUR❞ 먹는 거❣</p>
                <p>맛있는 걸 먹으면 설레고 행복해지는 편 !</p>
                <p>위 사진은 제가 먹어 본 만두 중에 제일 만두피가 쫀득했어요 ㅠ ㅠ 그래서 바로 사진을 찍어 둔...</p>
                <p>만두 좋아하시는 분들께 진짜 추천❕</p>
                <p>❝FIVE❞ 음악 듣기𝆕</p>
                <p>눈 뜨자마자 음악을 틀고 잘 때도 음악을 들으면서 자는 편</p>
                <p>그만큼 노래방도 너무너무 좋아해요☺</p>
                <p>❝SIX❞ 언니들 옷 뺏어 입기☠</p>
                <img src="{% static 'images/응응.jpg' %}" style="margin: 0 auto;" height="150" weigh="150" />
                <p>동생 있는 언니분들은 모두 화내시겠지만.. 언니 옷을 입는 게 제 취미..</p>
                <p>(물론 말하고 입어요..! 저 못된 사람은 아니에요....)</p>
                <p>제가 괜찮은 옷을 입으면 그건 언니 옷이고 누추한 옷을 입으면 그건 제 옷이라고 생각해 주시면 돼요 ^_^</p>
            </div>
            <div class="Childhood">
                <h1>Childhood</h1>
                <img src="{% static 'images/애기영신1.jpg' %}" style="margin: 0 auto;" height="150" weigh="160" />
                <img src="{% static 'images/애기영신2.jpg' %}" style="margin: 0 auto;" height="150" weigh="160" />
                <img src="{% static 'images/애기영신3.jpg' %}" style="margin: 0 auto;" height="150" weigh="160" />
            </div>
            <div class="hi">
                <p>마무리 짓기 위해 넣어 보는 사진들...</p>
                <p>애기 때부터 장난끼 넘쳐 보이는 사진들...</p>
                <p>지금도 변하지 않았으니 한 번 친해지기 시작하면 재밌을 거예요 히히</p>
            </div>
        </div>
        <div id="jb-footer">
            <p>2022년 4월 5일</p>
            <p>instagram ] @likelion_dongguk @dudtlstm</p>
            <p>e-mail ] annpys1024@naver.com</p>
        </div>
    </div>
</body>
</html>
{% endblock %}

sns_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>2022 Likelion Dongguk</title>
    <!--CSS-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Gaegu&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}">
</head>
<body>
    {% include 'shared/_navbar.html' %}

    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

sns_project/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{user.username}}
            </a>                
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'account_logout' %}">로그아웃</a></li>
                <li><a class="dropdown-item" href="{% url 'users:mypage'%}">Mypage</a></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'account_login' %}">로그인</a></li>
                <li><a class="dropdown-item" href="{% url 'account_signup' %}">회원가입</a></li>
                {% endif %}
            </ul>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
        </li>
        </ul>
        <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
    </div>
</nav>

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h1>{{user.username}}</h1>
    <br>
    <h3>게시글 목록</h3>
    <div>
        {% for post in posts %}
        <h5>{{post.title}}</h5>
        <h6>{{post.summary}}</h6>
        <a href="{% url 'main:detail' post.id %}">...자세히</a><hr>
        {% endfor %}
    </div>
</div>
{% endblock %}